# Generated by Django 4.1 on 2022-08-31 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('confiabilidade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('not_tem_codigo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crud.tema')),
            ],
        ),
    ]
