# Generated by Django 4.1 on 2022-08-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_noticias_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='confiabilidade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
