# Generated by Django 4.1 on 2022-08-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_noticia_confiabilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='confiabilidade',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
